try:
    print(y)
except:
    print("an exception occured")
finally:
    print ("finally block")
    


 
